=== EHB-MCT/web2-course-project-back-end-KatrijnDriesen/schema-wildewei_databank-inschrijvingen-standardJSON.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "email",
    "firstName",
    "idActiviteit",
    "lastName",
    "numberOfPeople",
    "sentEmail"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "email": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "idActiviteit": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "numberOfPeople": {
      "type": "string"
    },
    "sentEmail": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    }
  }
}

=== EHB-MCT/web2-course-project-back-end-KatrijnDriesen/wildewei_databank.inschrijvingen.json
[{
  "_id": {
    "$oid": "6957d459a69b930ccb837bc9"
  },
  "idActiviteit": "694413fccb79b2886705e926",
  "firstName": "test",
  "lastName": "test",
  "email": "",
  "numberOfPeople": "",
  "sentEmail": "Beste,\n        \n        Dank je voor je inschrijving voor de volgende activiteit: open tuindag.\n        We zien je graag op 2026-03-30T11:00:00.000Z om 2026-03-30T11:00:00.000Z.\n        \n        Gelieve binnen de tien werkdagen het bedrag van de inschrijving 0 over te schrijven op rekeningnummer BExx xxx xxx. Ter attentie van Wilde Wei, Gulle Gaard.\n        \n        Ik kijk er naar uit!\n        Met vriendelijke groet,\n        Katrien"
},
{
  "_id": {
    "$oid": "6957d45fa69b930ccb837bca"
  },
  "idActiviteit": "694413fccb79b2886705e926",
  "firstName": "test",
  "lastName": "test",
  "email": "test@katrijn.be",
  "numberOfPeople": "2",
  "sentEmail": "Beste,\n        \n        Dank je voor je inschrijving voor de volgende activiteit: open tuindag.\n        We zien je graag op 2026-03-30T11:00:00.000Z om 2026-03-30T11:00:00.000Z.\n        \n        Gelieve binnen de tien werkdagen het bedrag van de inschrijving 0 over te schrijven op rekeningnummer BExx xxx xxx. Ter attentie van Wilde Wei, Gulle Gaard.\n        \n        Ik kijk er naar uit!\n        Met vriendelijke groet,\n        Katrien"
}]
